name: Codecov
run-name: Test and Upload Code Coverage
on: [push]

jobs:
  Test-CodeCov:
    runs-on: ubuntu-latest
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.9"
      - name: Run Tests
        run: swift test --enable-code-coverage 
      - name: Convert to lcov
        run: llvm-cov export -format="lcov" .build/debug/swift-chess-neoPackageTests.xctest/Contents/MacOS/swift-chess-neoPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-actions@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: navanchauhan/swift-chess-neo
