name: Tests 
run-name: Run Tests
on: [push]

jobs:
  Test-CodeCov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.9"
      - name: Run Tests
        run: swift test --enable-code-coverage 
