name: Code Coverage 
on: [push]

jobs:
  Test-CodeCov:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Tests
        run: swift test --enable-code-coverage 
      - name: Convert to lcov
        run: llvm-cov export -format="lcov" .build/debug/swift-chess-neoPackageTests.xctest  -instr-profile .build/debug/codecov/default.profdata > info.lcov 
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
