name: Code Coverage 
on: [push]

jobs:
  Test-CodeCov:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Tests
        run: swift test --enable-code-coverage 
